### ISSUE TITLE
Taro 3.6.15闪退

### ISSUE THREAD

**Issue by wiilsliang** [robinv8/taro-rn-webpack5-demo#1]
环境信息: taro 3.6.15
                 taro ui  3.1.0
                 node 16.20.1 
执行步骤：
                git clone https://github.com/robinv8/taro-rn-webpack5-demo.git
                yarn
                yarn upgradePeerdeps
                yarn podInstall    
                yarn ios
结果:        模拟器闪退

**Comment by robinv8** [comment]
模拟器闪退，还是应用闪退？
xcode 有没有什么报错？

**Comment by wiilsliang** [comment]
> 模拟器闪退，还是应用闪退？ xcode 有没有什么报错？

自己解决了
